/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as appLayoutRouteImport } from "./pages/(app)/_layout";
import { Route as appHabitsRouteImport } from "./pages/(app)/habits";
import { Route as appOverviewRouteImport } from "./pages/(app)/overview";
import { Route as appTasksRouteImport } from "./pages/(app)/tasks";
import { Route as rootRouteImport } from "./pages/RootLayout";

const appTasksRoute = appTasksRouteImport.update({
  id: "/(app)/tasks",
  path: "/tasks",
  getParentRoute: () => rootRouteImport,
} as any);
const appOverviewRoute = appOverviewRouteImport.update({
  id: "/(app)/overview",
  path: "/overview",
  getParentRoute: () => rootRouteImport,
} as any);
const appHabitsRoute = appHabitsRouteImport.update({
  id: "/(app)/habits",
  path: "/habits",
  getParentRoute: () => rootRouteImport,
} as any);
const appLayoutRoute = appLayoutRouteImport.update({
  id: "/(app)/_layout",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/habits": typeof appHabitsRoute;
  "/overview": typeof appOverviewRoute;
  "/tasks": typeof appTasksRoute;
}
export interface FileRoutesByTo {
  "/habits": typeof appHabitsRoute;
  "/overview": typeof appOverviewRoute;
  "/tasks": typeof appTasksRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/(app)/_layout": typeof appLayoutRoute;
  "/(app)/habits": typeof appHabitsRoute;
  "/(app)/overview": typeof appOverviewRoute;
  "/(app)/tasks": typeof appTasksRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/habits" | "/overview" | "/tasks";
  fileRoutesByTo: FileRoutesByTo;
  to: "/habits" | "/overview" | "/tasks";
  id:
    | "__root__"
    | "/(app)/_layout"
    | "/(app)/habits"
    | "/(app)/overview"
    | "/(app)/tasks";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  appLayoutRoute: typeof appLayoutRoute;
  appHabitsRoute: typeof appHabitsRoute;
  appOverviewRoute: typeof appOverviewRoute;
  appTasksRoute: typeof appTasksRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(app)/tasks": {
      id: "/(app)/tasks";
      path: "/tasks";
      fullPath: "/tasks";
      preLoaderRoute: typeof appTasksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(app)/overview": {
      id: "/(app)/overview";
      path: "/overview";
      fullPath: "/overview";
      preLoaderRoute: typeof appOverviewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(app)/habits": {
      id: "/(app)/habits";
      path: "/habits";
      fullPath: "/habits";
      preLoaderRoute: typeof appHabitsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(app)/_layout": {
      id: "/(app)/_layout";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof appLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  appLayoutRoute: appLayoutRoute,
  appHabitsRoute: appHabitsRoute,
  appOverviewRoute: appOverviewRoute,
  appTasksRoute: appTasksRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
